### ISSUE TITLE
The Create user fields resets after it throws an error 

### ISSUE THREAD

**Issue by JeelRajodiya** [JeelRajodiya/clash-of-codes#18]
![image](https://github.com/JeelRajodiya/clash-of-codes/assets/63534268/e76d0631-0e88-4a2d-bffd-95aa7a28b185)

see name and email is reset
![image](https://github.com/JeelRajodiya/clash-of-codes/assets/63534268/1cf8c68d-d641-4385-96fa-37716988d69b)

**Comment by Codesmith28** [comment]
![image](https://github.com/JeelRajodiya/clash-of-codes/assets/117557273/7ced2307-f44d-43ab-9d40-dc84a0e82cc0)

thanks to this

**Comment by Codesmith28** [comment]
i think i resolved this with #19
