### ISSUE TITLE
Please select a clan error resets as well 

### ISSUE THREAD

**Issue by JeelRajodiya** [JeelRajodiya/clash-of-codes#19]
![image](https://github.com/JeelRajodiya/clash-of-codes/assets/63534268/cbadcd34-a759-4670-9421-19c28d54aca0)
I selected None as a clan so it throwed an error, also reset all the fields 
![image](https://github.com/JeelRajodiya/clash-of-codes/assets/63534268/074be18c-3dc1-42a6-a96f-ddc7cc9bd23c)

**Comment by Codesmith28** [comment]
elaborate

**Comment by JeelRajodiya** [comment]
> elaborate

When the error comes "Please select a clan" it also resets the all the input fields as well. so i will have to re enter the details
