### ISSUE TITLE
When I edit a user who do not have a cfUsername, it is showing username in edit box undefined 

### ISSUE THREAD

**Issue by JeelRajodiya** [JeelRajodiya/clash-of-codes#20]
![image](https://github.com/JeelRajodiya/clash-of-codes/assets/63534268/1adb63ce-0f82-403b-b4ab-592bd377e54f)

**Comment by Codesmith28** [comment]
what?

**Comment by JeelRajodiya** [comment]
> what?

Yes

**Comment by Codesmith28** [comment]
taare su joiye che toh?

**Comment by JeelRajodiya** [comment]
> taare su joiye che toh?

Ae field undefined ne badle empty hovi joi ae

**Comment by Codesmith28** [comment]
![image](https://github.com/JeelRajodiya/clash-of-codes/assets/117557273/f1810760-d104-400e-ad08-da31b26aebea)
ae toh type aj evi define kreli che
