### ISSUE TITLE
Reduce the gap on config page 

### ISSUE THREAD

**Issue by JeelRajodiya** [JeelRajodiya/clash-of-codes#4]
pink gap was 64 i reduced to 32
![image](https://github.com/JeelRajodiya/clash-of-codes/assets/63534268/406fed72-5a10-4675-b9ae-13b1356fc89e)

**Comment by JeelRajodiya** [comment]
it's still 64

**Comment by Codesmith28** [comment]
![image](https://github.com/JeelRajodiya/clash-of-codes/assets/117557273/e70dc8a4-522e-49af-ab3e-ab6df5e1db4b)

brober toh dekhai che
