### ISSUE TITLE
Reduce the gap on users page 

### ISSUE THREAD

**Issue by JeelRajodiya** [JeelRajodiya/clash-of-codes#5]
Again the pink valo gap was 64, I reduced it to 32 
![image](https://github.com/JeelRajodiya/clash-of-codes/assets/63534268/5d7c0b3e-afd1-4eeb-8a43-89800636085f)

**Comment by JeelRajodiya** [comment]
@Codesmith28 it's still 64 
![image](https://github.com/JeelRajodiya/clash-of-codes/assets/63534268/c9fd929a-d402-4b52-8b81-e9aecaf6bf4e)

**Comment by Codesmith28** [comment]
but that is not the pink vaalo gap

**Comment by Codesmith28** [comment]
> @Codesmith28 it's still 64 ![image](https://private-user-images.githubusercontent.com/63534268/291924606-c9fd929a-d402-4b52-8b81-e9aecaf6bf4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMzYwNTQsIm5iZiI6MTcwMzEzNTc1NCwicGF0aCI6Ii82MzUzNDI2OC8yOTE5MjQ2MDYtYzlmZDkyOWEtZDQwMi00YjUyLThiODEtZTlhZWNhZjZiZjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA1MTU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMzI2MjQzZmI0MmViZTZlZDRlNjc3NTUxYzE5Njg1Y2NlYjk0ZDFlZTIyY2FhNGU4Y2U1YmMwYjAzODJjZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IxdRdUKvNHPTjbqTPMUL-zhkkmnpQLMBDay7pbKjnQY)


![image](https://github.com/JeelRajodiya/clash-of-codes/assets/117557273/b0072aa3-6e09-43b4-a925-a52e7dc6eb6c)
